name: CI Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.vscode/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Linting
        run: |
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          pylint service tests --max-line-length=127

      - name: Run unit tests
        run: |
          export FLASK_APP=service:app
          pytest --pspec --cov=service --cov-fail-under=95 --disable-warnings
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@localhost:5432/testdb"

      - name: Upload code coverage
        uses: codecov/codecov-action@v4.6.0
